DEF VAR CLAVE AS CHARACTER.
DEF VAR DESCRIPCION AS CHARACTER.
DEF VAR PRECIO AS DECIMAL.
DEF VAR NUMCAT AS INTEGER.

INPUT FROM C:\PRECIOS.CSV.

OUTPUT TO C:\PREFIN.CSV.

REPEAT:
    IMPORT DELIMITER "," CLAVE DESCRIPCION PRECIO NUMCAT.
    EXPORT DELIMITER "," CLAVE DESCRIPCION (PRECIO + 9) NUMCAT.
END.

OUTPUT CLOSE.
INPUT CLOSE.
